name: channelvit
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=12.1  # comment/remove if no GPU
  - cudatoolkit=12.1   # for older setups
  - pip
  - pip:
      - timm>=1.0.8
      - lightning>=2.2.5
      - numpy
      - pandas
      - scikit-learn
      - matplotlib
      - pillow
      - rasterio
      - geopandas
      - hydra-core
      - omegaconf
      - wandb
      - tqdm
      - ruff
      - black
      - pytest
